name: Build

on:
  push:
    branches-ignore:
      - 'gh-pages'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on:
      - self-hosted
      - linux
      - x64
      - gpu

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          npm ci --prefix processing
          npm ci --prefix site
          ./build_all_branches.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
